name: tvip_labs_test_excercise
description: "Test excercise for TVIP LABS company"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  auto_route: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0

flutter:
  generate: true

  uses-material-design: true